#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloAndroid.Resource", IsApplication=true)]

namespace HelloAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_dialog_actioned_on_disabled_toast = global::HelloAndroid.Resource.String.mobile_center_distribute_dialog_actioned_on_disabled_toast;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_download_progress_number_format = global::HelloAndroid.Resource.String.mobile_center_distribute_download_progress_number_format;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_downloading_mandatory_update = global::HelloAndroid.Resource.String.mobile_center_distribute_downloading_mandatory_update;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_install = global::HelloAndroid.Resource.String.mobile_center_distribute_install;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_install_ready_message = global::HelloAndroid.Resource.String.mobile_center_distribute_install_ready_message;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_install_ready_title = global::HelloAndroid.Resource.String.mobile_center_distribute_install_ready_title;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_unknown_sources_dialog_message = global::HelloAndroid.Resource.String.mobile_center_distribute_unknown_sources_dialog_message;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_unknown_sources_dialog_settings = global::HelloAndroid.Resource.String.mobile_center_distribute_unknown_sources_dialog_settings;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_download = global::HelloAndroid.Resource.String.mobile_center_distribute_update_dialog_download;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_message_mandatory = global::HelloAndroid.Resource.String.mobile_center_distribute_update_dialog_message_mandatory;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_message_optional = global::HelloAndroid.Resource.String.mobile_center_distribute_update_dialog_message_optional;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_postpone = global::HelloAndroid.Resource.String.mobile_center_distribute_update_dialog_postpone;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_title = global::HelloAndroid.Resource.String.mobile_center_distribute_update_dialog_title;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_view_release_notes = global::HelloAndroid.Resource.String.mobile_center_distribute_update_dialog_view_release_notes;
			global::Microsoft.Azure.Mobile.Push.Android.Resource.Integer.google_play_services_version = global::HelloAndroid.Resource.Integer.google_play_services_version;
			global::Microsoft.Azure.Mobile.Push.Android.Resource.String.common_google_play_services_unknown_issue = global::HelloAndroid.Resource.String.common_google_play_services_unknown_issue;
			global::Microsoft.Azure.Mobile.Push.Android.Resource.String.library_name = global::HelloAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int sayHello = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int showHello = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050011
			public const int ApplicationName = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int Hello = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int library_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int mobile_center_distribute_dialog_actioned_on_disabled_toast = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int mobile_center_distribute_download_progress_number_format = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int mobile_center_distribute_downloading_mandatory_update = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int mobile_center_distribute_install = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int mobile_center_distribute_install_ready_message = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int mobile_center_distribute_install_ready_title = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int mobile_center_distribute_unknown_sources_dialog_message = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int mobile_center_distribute_unknown_sources_dialog_settings = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int mobile_center_distribute_update_dialog_download = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int mobile_center_distribute_update_dialog_message_mandatory = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int mobile_center_distribute_update_dialog_message_optional = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int mobile_center_distribute_update_dialog_postpone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int mobile_center_distribute_update_dialog_title = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int mobile_center_distribute_update_dialog_view_release_notes = 2131034127;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
